import type { NodeDetail } from './types';

/** Mock detail payloads keyed by graph node id. */
export const detailFixtures: Record<string, NodeDetail> = {
  'task-1': {
    kind: 'task',
    role: 'entity',
    nodeId: 'task-1',
    title: 'task',
    subtitle: 'Unit of work that drives a worktree stream',
    description: 'Fix login rate limit when agent-run retries',
    slug: 'fix-login-rate',
    status: 'in_progress',
    owner: 'alice',
    createdAt: '2026-07-10',
    linkedWorktreeId: 'wt-1',
    linkedWorktreeLabel: 'worktree 1',
  },
  'task-2': {
    kind: 'task',
    role: 'entity',
    nodeId: 'task-2',
    title: 'task',
    subtitle: 'Unit of work that drives a worktree stream',
    description: 'Document wrk --web SPA routes',
    slug: 'docs-wrk-web',
    status: 'open',
    owner: 'bob',
    createdAt: '2026-07-11',
    linkedWorktreeId: 'wt-2',
    linkedWorktreeLabel: 'worktree 2',
  },
  'wt-1': {
    kind: 'worktree',
    role: 'entity',
    nodeId: 'wt-1',
    title: 'worktree 1',
    subtitle: 'Linked checkout (isolated branch)',
    path: '/Users/you/.wrk/worktrees/dot-pkgs-master-2026-07-10',
    branch: 'master-2026-07-10',
    baseBranch: 'master',
    clean: false,
    dirtyFileCount: 3,
    ahead: 2,
    behind: 0,
    taskId: 'task-1',
    taskSlug: 'fix-login-rate',
  },
  'wt-2': {
    kind: 'worktree',
    role: 'entity',
    nodeId: 'wt-2',
    title: 'worktree 2',
    subtitle: 'Linked checkout (isolated branch)',
    path: '/Users/you/.wrk/worktrees/dot-pkgs-master-2026-07-11',
    branch: 'master-2026-07-11',
    baseBranch: 'master',
    clean: true,
    ahead: 0,
    behind: 1,
    taskId: 'task-2',
    taskSlug: 'docs-wrk-web',
  },
  main: {
    kind: 'main',
    role: 'entity',
    nodeId: 'main',
    title: 'Main',
    subtitle: 'Primary repository checkout',
    path: '/Users/you/src/dot-pkgs',
    branch: 'master',
    commit: 'a1b2c3d',
    subject: 'Merge worktree: login rate limit',
    clean: true,
    worktreeCount: 2,
    worktreeLabels: ['worktree 1', 'worktree 2'],
  },
  remote: {
    kind: 'remote',
    role: 'entity',
    nodeId: 'remote',
    title: 'Remote',
    subtitle: 'Upstream hosting (origin)',
    name: 'origin',
    url: 'git@github.com:xhd2015/dot-pkgs.git',
    defaultBranch: 'master',
    lastFetchAt: '2026-07-12T09:14:02Z',
    trackingSummary: 'Main ↔ origin/master — identical (mock)',
  },
  'chg-1': {
    kind: 'changes',
    role: 'state',
    nodeId: 'chg-1',
    title: 'changes',
    subtitle: 'Uncommitted / unstaged work relative to HEAD',
    scope: 'worktree',
    scopeLabel: 'worktree 1 (wt-1)',
    summary: '2 modified · 1 untracked',
    dirtyFiles: [
      { path: 'go-pkgs/wrkcli/run.go', status: 'M' },
      { path: 'wrk-react/App.tsx', status: 'M' },
      { path: 'tmp/notes.md', status: '??' },
    ],
  },
  'chg-2': {
    kind: 'changes',
    role: 'state',
    nodeId: 'chg-2',
    title: 'changes',
    subtitle: 'Uncommitted / unstaged work relative to HEAD',
    scope: 'worktree',
    scopeLabel: 'worktree 2 (wt-2)',
    summary: 'clean working tree',
    dirtyFiles: [],
  },
  'chg-main': {
    kind: 'changes',
    role: 'state',
    nodeId: 'chg-main',
    title: 'changes',
    subtitle: 'Uncommitted / unstaged work relative to HEAD',
    scope: 'main',
    scopeLabel: 'Main',
    summary: '1 modified',
    dirtyFiles: [{ path: 'README.md', status: 'M' }],
  },
  'rebase-1': {
    kind: 'action',
    role: 'action',
    nodeId: 'rebase-1',
    title: 'rebase',
    subtitle: 'Replay worktree branch onto Main',
    action: 'rebase',
    targetLabel: 'worktree 1',
    description: 'Replay worktree branch onto Main',
    steps: [
      'fetch / compare base',
      'git rebase Main',
      'report conflicts or clean',
    ],
    params: [
      { key: 'target worktree', value: 'worktree 1' },
      { key: 'base', value: 'Main / master' },
    ],
  },
  'rebase-2': {
    kind: 'action',
    role: 'action',
    nodeId: 'rebase-2',
    title: 'rebase',
    subtitle: 'Replay worktree branch onto Main',
    action: 'rebase',
    targetLabel: 'worktree 2',
    description: 'Replay worktree branch onto Main',
    steps: [
      'fetch / compare base',
      'git rebase Main',
      'report conflicts or clean',
    ],
    params: [
      { key: 'target worktree', value: 'worktree 2' },
      { key: 'base', value: 'Main / master' },
    ],
  },
  sync: {
    kind: 'action',
    role: 'action',
    nodeId: 'sync',
    title: 'sync',
    subtitle: 'Merge worktree work back into Main',
    action: 'sync',
    targetLabel: 'Main',
    description: 'Fan-in from worktree land into Main (mock)',
    steps: ['clean check', 'merge-back', 'sync complete'],
    params: [{ key: 'target', value: 'Main' }],
  },
  tag: {
    kind: 'action',
    role: 'action',
    nodeId: 'tag',
    title: 'tag',
    subtitle: 'Mark a release point on Main',
    action: 'tag',
    targetLabel: 'Main',
    description: 'Create an annotated tag on Main HEAD',
    steps: ['read HEAD', 'create annotated tag', 'tag ready locally'],
    params: [
      { key: 'applies to', value: 'Main' },
      { key: 'name template', value: 'v0.0.0-mock' },
    ],
  },
  push: {
    kind: 'action',
    role: 'action',
    nodeId: 'push',
    title: 'push',
    subtitle: 'Publish Main (and tags) to Remote',
    action: 'push',
    targetLabel: 'origin (Remote)',
    description: 'Push Main to origin',
    steps: ['resolve origin', 'git push', 'push accepted'],
    params: [
      { key: 'from', value: 'Main' },
      { key: 'to', value: 'origin (Remote)' },
    ],
  },
  'agent-1': {
    kind: 'agent-run',
    role: 'action',
    nodeId: 'agent-1',
    title: 'agent-run',
    subtitle: 'Launch agent session in a worktree',
    action: 'agent-run',
    runner: 'default',
    worktreeLabel: 'worktree 1',
    promptPreview: 'Continue task: fix-login-rate …',
    sessionHint: 'session opened (mock) — see Logs when run from graph',
  },
  'agent-2': {
    kind: 'agent-run',
    role: 'action',
    nodeId: 'agent-2',
    title: 'agent-run',
    subtitle: 'Launch agent session in a worktree',
    action: 'agent-run',
    runner: 'default',
    worktreeLabel: 'worktree 2',
    promptPreview: 'Continue task: docs-wrk-web …',
    sessionHint: 'session opened (mock) — see Logs when run from graph',
  },
};

export function getDetail(nodeId: string | null): NodeDetail | null {
  if (!nodeId) return null;
  return detailFixtures[nodeId] ?? null;
}
